### ISSUE TITLE
ImportError: cannot import name 'speech' from 'google.cloud' (unknown location)

### ISSUE THREAD

**Issue by SoYoungCho** [2021-KPANG/AI-Online-Meeting-Solution#4]
```
Traceback (most recent call last):
  File "C:/Users/Soyoung Cho/Desktop/2021/KPMG 공모전/AI-Online-Meeting-Solution-main/app.py", line 7, in <module>
    import googleAPI
  File "C:\Users\Soyoung Cho\Desktop\2021\KPMG 공모전\AI-Online-Meeting-Solution-main\googleAPI.py", line 2, in <module>
    from google.cloud import speech
ImportError: cannot import name 'speech' from 'google.cloud' (unknown location)
```

해결 방법 아실까요?

**Comment by SoYoungCho** [comment]
```
pip install googleAPI
pip install google.cloud
```
위 커멘드로 설치는 했습니다!

**Comment by SoYoungCho** [comment]
README 수정 감사합니다.
